@startuml
!include <archimate/Archimate>

' Elements

Technology_Service(rms, "rms")

'Application_Service(a, "刺探")

Technology_Service(电核, "电核")
Technology_Service(电核Plugin, "浏览器插件")
Technology_Service(webServer, "web服务器")

'Relationships
Rel_Serving_Up(rms, 电核, "")
Rel_Serving_Up(电核Plugin, rms, "")
Rel_Aggregation_Right(电核, 电核Plugin, "")
Rel_Serving_Up(webServer, 电核, "")
@enduml