@startuml
'!define Junction_Or circle #black
'!define Junction_And circle #whitesmoke
rectangle AliceBlue #AliceBlue
rectangle AntiqueWhite #AntiqueWhite
rectangle Aqua #Aqua
rectangle Aquamarine #Aquamarine
rectangle Azure #Azure
rectangle Beige #Beige
rectangle Bisque #Bisque
rectangle Black #Black
rectangle BlanchedAlmond #BlanchedAlmond
rectangle Blue #Blue
rectangle BlueViolet #BlueViolet
rectangle Brown #Brown
rectangle BurlyWood #BurlyWood
rectangle CadetBlue #CadetBlue
rectangle Chartreuse #Chartreuse
rectangle Chocolate #Chocolate
rectangle Coral #Coral
rectangle CornflowerBlue #CornflowerBlue
rectangle Cornsilk #Cornsilk
rectangle Crimson #Crimson
rectangle Cyan #Cyan
rectangle DarkBlue #DarkBlue
rectangle DarkCyan #DarkCyan
rectangle DarkGoldenRod #DarkGoldenRod
rectangle DarkGray #DarkGray
rectangle DarkGrey #DarkGrey
rectangle DarkGreen #DarkGreen
rectangle DarkKhaki #DarkKhaki
rectangle DarkMagenta #DarkMagenta
rectangle DarkOliveGreen #DarkOliveGreen
rectangle Darkorange #Darkorange
rectangle DarkOrchid #DarkOrchid
rectangle DarkRed #DarkRed
rectangle DarkSalmon #DarkSalmon
rectangle DarkSeaGreen #DarkSeaGreen
rectangle DarkSlateBlue #DarkSlateBlue
rectangle DarkSlateGray #DarkSlateGray
rectangle DarkSlateGrey #DarkSlateGrey
rectangle DarkTurquoise #DarkTurquoise
rectangle DarkViolet #DarkViolet
rectangle DeepPink #DeepPink
rectangle DeepSkyBlue #DeepSkyBlue
rectangle DimGray #DimGray
rectangle DimGrey #DimGrey
rectangle DodgerBlue #DodgerBlue
rectangle FireBrick #FireBrick
rectangle FloralWhite #FloralWhite
rectangle ForestGreen #ForestGreen
rectangle Fuchsia #Fuchsia
rectangle Gainsboro #Gainsboro
rectangle GhostWhite #GhostWhite
rectangle Gold #Gold
rectangle GoldenRod #GoldenRod
rectangle Gray #Gray
rectangle Grey #Grey
rectangle Green #Green
rectangle GreenYellow #GreenYellow
rectangle HoneyDew #HoneyDew
rectangle HotPink #HotPink
rectangle IndianRed #IndianRed
rectangle Indigo #Indigo
rectangle Ivory #Ivory
rectangle Khaki #Khaki
rectangle Lavender #Lavender
rectangle LavenderBlush #LavenderBlush
rectangle LawnGreen #LawnGreen
rectangle LemonChiffon #LemonChiffon
rectangle LightBlue #LightBlue
rectangle LightCoral #LightCoral
rectangle LightCyan #LightCyan
rectangle LightGoldenRodYellow #LightGoldenRodYellow
rectangle LightGray #LightGray
rectangle LightGrey #LightGrey
rectangle LightGreen #LightGreen
rectangle LightPink #LightPink
rectangle LightSalmon #LightSalmon
rectangle LightSeaGreen #LightSeaGreen
rectangle LightSkyBlue #LightSkyBlue
rectangle LightSlateGray #LightSlateGray
rectangle LightSlateGrey #LightSlateGrey
rectangle LightSteelBlue #LightSteelBlue
rectangle LightYellow #LightYellow
rectangle Lime #Lime
rectangle LimeGreen #LimeGreen
rectangle Linen #Linen
rectangle Magenta #Magenta
rectangle Maroon #Maroon
rectangle MediumAquaMarine #MediumAquaMarine
rectangle MediumBlue #MediumBlue
rectangle MediumOrchid #MediumOrchid
rectangle MediumPurple #MediumPurple
rectangle MediumSeaGreen #MediumSeaGreen
rectangle MediumSlateBlue #MediumSlateBlue
rectangle MediumSpringGreen #MediumSpringGreen
rectangle MediumTurquoise #MediumTurquoise
rectangle MediumVioletRed #MediumVioletRed
rectangle MidnightBlue #MidnightBlue
rectangle MintCream #MintCream
rectangle MistyRose #MistyRose
rectangle Moccasin #Moccasin
rectangle NavajoWhite #NavajoWhite
rectangle Navy #Navy
rectangle OldLace #OldLace
rectangle Olive #Olive
rectangle OliveDrab #OliveDrab
rectangle Orange #Orange
rectangle OrangeRed #OrangeRed
rectangle Orchid #Orchid
rectangle PaleGoldenRod #PaleGoldenRod
rectangle PaleGreen #PaleGreen
rectangle PaleTurquoise #PaleTurquoise
rectangle PaleVioletRed #PaleVioletRed
rectangle PapayaWhip #PapayaWhip
rectangle PeachPuff #PeachPuff
rectangle Peru #Peru
rectangle Pink #Pink
rectangle Plum #Plum
rectangle PowderBlue #PowderBlue
rectangle Purple #Purple
rectangle Red #Red
rectangle RosyBrown #RosyBrown
rectangle RoyalBlue #RoyalBlue
rectangle SaddleBrown #SaddleBrown
rectangle Salmon #Salmon
rectangle SandyBrown #SandyBrown
rectangle SeaGreen #SeaGreen
rectangle SeaShell #SeaShell
rectangle Sienna #Sienna
rectangle Silver #Silver
rectangle SkyBlue #SkyBlue
rectangle SlateBlue #SlateBlue
rectangle SlateGray #SlateGray
rectangle SlateGrey #SlateGrey
rectangle Snow #Snow
rectangle SpringGreen #SpringGreen
rectangle SteelBlue #SteelBlue
rectangle Tan #Tan
rectangle Teal #Teal
rectangle Thistle #Thistle
rectangle Tomato #Tomato
rectangle Turquoise #Turquoise
rectangle Violet #Violet
rectangle Wheat #Wheat
rectangle White #White
rectangle WhiteSmoke #WhiteSmoke
rectangle Yellow #Yellow
rectangle YellowGreen #YellowGreen
'rectangle #Archimate
rectangle BUSINESS #BUSINESS
rectangle APPLICATION #APPLICATION
rectangle MOTIVATION #MOTIVATION
rectangle STRATEGY #STRATEGY
rectangle TECHNOLOGY #TECHNOLOGY
rectangle PHYSICAL #PHYSICAL
rectangle IMPLEMENTATION #IMPLEMENTATION

@enduml