@startuml
skinparam responseMessageBelowArrow true
hide unlinked
participant 数仓 as s
participant 资产池 as z
participant 友信 as y
participant 富盈 as f
autonumber
s -> z : 推送账单数据到 order_debt_list
activate y #FFBBBB
||25|
'autonumber2.1
z -> y: 提交资产审核
y -[#red]> f: 决策结果
deactivate y
hnote right: 资金募集

'autonumber3

return 结果推送外部

@enduml


